#!/bin/sh
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
output_file="$project_dir/manuscript.md"
temp_file=$(mktemp "${TMPDIR:-/tmp}/hellochildren.XXXXXX")
trap 'rm -f "$temp_file"' EXIT HUP INT TERM

printf '<!-- Generated by ./build.sh; edit chapters/*.md instead. -->\n\n' > "$temp_file"
for chapter_file in "$project_dir"/chapters/*.md; do
    cat "$chapter_file" >> "$temp_file"
    printf '\n\n' >> "$temp_file"
done
mv "$temp_file" "$output_file"
trap - EXIT HUP INT TERM
